version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: test_service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: test_service
    ports:
      - "5435:5435"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
