// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: integrations.sql

package sqlc

import (
	"context"
)

const listIntegrations = `-- name: ListIntegrations :many
SELECT id, name, created_at, updated_at, deleted_at FROM integrations
`

func (q *Queries) ListIntegrations(ctx context.Context) ([]Integration, error) {
	rows, err := q.db.Query(ctx, listIntegrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Integration
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
