// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlc

import (
	"context"
)

type Querier interface {
	ListIntegrations(ctx context.Context) ([]Integration, error)
}

var _ Querier = (*Queries)(nil)
